CREATE DATABASE reto_9;
USE reto_9;

CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(40),
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE messsages(
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(40) NOT NULL ,
    description VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    user_id INT,

    FOREIGN KEY (user_id) REFERENCES users(id) 
);


CREATE TABLE dates(
	id INT AUTO_INCREMENT PRIMARY KEY,
    date INT NOT NULL,
    hour INT NOT NULL,
    place VARCHAR(40) NOT NULL ,
    
    user_id INT,
    
    FOREIGN KEY (user_id) REFERENCES users(id) 
);

CREATE TABLE comments(
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(40) NOT NULL ,
    description VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    user_id INT,
    
    FOREIGN KEY (user_id) REFERENCES users(id) 
);
